### ISSUE TITLE
Prototype naar HTML (All webinars)

### ISSUE THREAD

**Issue by Saif8599** [Saif8599/the-client-website#1]
### Schetsen & Wireframes 
**Webinar-pagina**

## Sitemap
Allereerst ben ik begonnen met het maken van een sitemap. Dit gaf me een goed overzicht van de structuur van de website en hoe de verschillende pagina’s met elkaar verbonden zijn.

![image](https://github.com/user-attachments/assets/63691b6c-e54e-467e-b2eb-7b8139c08623)

## Wireframe/Wireflow
Om een goed idee te krijgen van de lay-out en gebruikerservaring, heb ik eerst wireframes gemaakt. Deze wireframes heb ik vervolgens omgezet in wireflows, zodat ik inzicht kreeg in de interacties en hoe de gebruiker door de pagina navigeert.

![image](https://github.com/user-attachments/assets/1ec96722-8544-4dbd-8409-0129ba9c34da)

## Responsive Design
Nadat de wireflows waren afgerond, heb ik me gefocust op het responsive design. Ik heb hierbij een mobile-first methode gebruikt.

![image](https://github.com/user-attachments/assets/0d8c4a1d-d47e-4cb5-beaf-b940289df210)

## Breakdown Schets
Daarna ben ik verder gegaan met het maken van een breakdown schets voor de webinar-pagina. Deze schets laat precies zien welke onderdelen en elementen er op de pagina moeten komen, en hoe deze ingedeeld moeten worden.

![image](https://github.com/user-attachments/assets/ded92237-6b5f-41a4-88f8-162ecf651a09)

**Comment by Saif8599** [comment]
### W3C HTML Validator

Geen errors, wel info.

https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fsaif8599.github.io%2Fthe-client-website%2Fpages%2Fall-webinars.html

**Comment by Saif8599** [comment]
### Starting point nav, header & main 

https://github.com/Saif8599/the-client-website/commit/44f4061a121b681c841ed6a0d6acb6703824b985

**Comment by Saif8599** [comment]
### Figma

https://www.figma.com/design/PbMAVjDmeSEX5hj85mbNhB/Webinar-RT?node-id=0-1&m=dev&t=oQCSpdJlInMlxRuM-1

![image](https://github.com/user-attachments/assets/21398603-3393-4c04-af57-4c99867e14d2)

**Comment by Naddybs** [comment]
Je schetsen zien er over het algemeen goed uit! Goed dat je dingen aanduid met kleuren en pijlen, dit zorgt voor meer overzicht. Goed bezig!! 🙃
