### ISSUE TITLE
Knoop : Sprint review

### ISSUE THREAD

**Issue by KoopReynders** [Saif8599/the-client-website#13]
Je demonstreert je website op mobiel en desktop view. Je maakt niet duidelijk waar je feedback op wil en je begint niet met het doel van jouw demonstratie, probeer dat de volgende keer wel te doen. Je hebt nog geen plaatjes in je website maar een soort placeholders. Vervang die snel voor stock images, dan krijg je al een beter beeld van hoe de website er uit gaat komen te zien.

**Comment by Saif8599** [comment]
https://github.com/Saif8599/all-human-accessible-website/commit/f2198cee79783c54d16725d89e597946e8164d01
