### ISSUE TITLE
Semantische HTML structuur

### ISSUE THREAD

**Issue by Naddybs** [Saif8599/the-client-website#2]
[Uitleg over semantische HTML](https://web.dev/learn/html/semantic-html)
[Elementen die je kan gebruiken ipv divs](https://medium.com/shecodeafrica/html-tags-to-use-instead-of-div-dbfab613a5cc#:~:text=The%20article%20tag%20is%20mainly,style%20it%20to%20your%20taste.)

https://github.com/Saif8599/the-client-website/blob/63e0735e8e1041f3fc8150e87883f46049ce5d63/pages/all-webinars.html#L9-L20

In de bovenstaande code voorbeeld heb je allereerst alle elementen voor de navigatie in de nav element gezet. Dit is correct, eronder heb je heb je de eerste content in de header geplaatst. Om een semantische structuur te creëren kan je het beste de navigatie binnen de header plaatsen en de kerninhoud in de main. Dit zorgt voor een duidelijke structuur en leesbare code.

https://github.com/Saif8599/the-client-website/blob/63e0735e8e1041f3fc8150e87883f46049ce5d63/pages/all-webinars.html#L67-L84

In je code gebruik je ook vaak het div element om verschillende webinar-items weer te geven, wat functioneel werkt, maar geen betekenis toevoegt aan de structuur van je HTML. Omdat je hier een lijst van verschillende items wilt weergeven, zoals webinars, is het beter om een ul (onordende lijst) met li elementen te gebruiken.

### `Waarom is dit beter?`
- **Betekenisvolle structuur:** Een lijst geeft direct aan dat er een verzameling van items is. Dit helpt zoekmachines en browsers de inhoud beter te begrijpen, wat kan bijdragen aan de toegankelijkheid.

- **Leesbaarheid:** Door een lijst te gebruiken in plaats van losse div elementen, maak je de code duidelijker en logischer voor anderen die eraan werken. Het maakt de structuur van de HTML overzichtelijker en eenvoudiger te begrijpen.

- **Toegankelijkheid:** Screenreaders en andere hulpmiddelen voor mensen met een beperking herkennen lijsten automatisch en kunnen de inhoud op een meer gebruiksvriendelijke manier presenteren. Ze vertellen gebruikers bijvoorbeeld hoeveel items er in de lijst staan, wat niet gebeurt met div elementen.

**Comment by Saif8599** [comment]
Ik heb de navbar nu in de header gezet en de div's veranderd naar article met h3's.

https://github.com/Saif8599/the-client-website/commit/ecba5a1b59172c7661b5800d44a888d2b359e5eb
