### ISSUE TITLE
Code/Design Review

### ISSUE THREAD

**Issue by irisvw** [Saif8599/the-client-website#3]
**HTML**
- HTML validator geeft geen errors: wel geeft deze een aandachtspuntje over "Trailing slash on void elements" op je img elementen.
- Als de nav onderdeel is van de header, is het wellicht netjes om deze in de header te nesten.
- De structuur lijkt logisch en bruikbaar.
- Als de p elementen onder de foto's beschrijvingen zijn van de foto's, is het beter om een figure te gebruiken met een figcaption.

**Ontwerp**
De hele pagina is vormgegeven, het ontwerp is duidelijk, en er is rekening gehouden met verschillende schermformaten. Visuele hierarchie lijkt ook duidelijk, al kan het misschien iets duidelijker in de breakdown schets door gebruik te maken van verschillende diktes en kleur.

**Comment by Saif8599** [comment]
ik heb de p element veranderd naar h3 voor de article's. 
https://github.com/Saif8599/the-client-website/commit/ecba5a1b59172c7661b5800d44a888d2b359e5eb
